<link rel="stylesheet" type="text/css" media="screen" href="/styles/fullcalendar.css" />
<!-- <link rel="stylesheet" type="text/css" media="screen" href="/styles/fullcalendar.print.css" />
 -->
<script type="text/javascript" src="/scripts/jquery.min.js"></script>
<script type="text/javascript" src="/scripts/jquery-ui.custom.min.js"></script>
<script type="text/javascript" src="/scripts/fullcalendar.min.js"></script>
<script type="text/javascript" src="/scripts/fullcalendar.js"></script>

<section>
	<div class="section">
			<h3>When Are You Free?</h3>
</head>
<body class="calendar-body">
	<div id='calendar'></div>
</body>
</div>
</section>
</html>