<link rel="stylesheet" type="text/css" media="screen" href="/styles/people.css" />
<script type="text/javascript" src="/scripts/people.js"></script>

<section class="clearfix">
	<div id="upper-close" class="upper-div-text">
		<strong>No Plans on Thursday?</strong> Hang out with your friends! They don't have any plans :)<span onclick="upperClose()" class="glyphicon glyphicon-remove float-right glysize"></span>
	</div>
	<h3>1. Choose People</h3>
	<br>
	<div class="select">
		<h4 class="float-left try">My Friends</h4><h4 class="float-left"> <a href="#"> Random People</a></h4>
		<div class="float-right">
			<form method="post">
				<select class="select-date" name="date-range">
					<option <?php if ($dateRange=='This Week')echo "selected" ?> >This Week</option>
					<option <?php if ($dateRange=='Next Week')echo "selected" ?> >Next Week</option>
				</select>
			</form>
		</div>
	</div>
	<div class="whole-people clearfix">
		<p>Choose from:</p>
		<?php foreach ($users as $user): ?>
			<div id="" class="people-info">
				<img class="img-people" src="<?php echo 'https://scontent-b-lax.xx.fbcdn.net/hphotos-prn2/l/t1.0-9/1382273_556640624407879_1732563799_n.jpg'; ?>">
				<p class="name-people"><a href="<?php //echo $user['user_url'];?>"><?php echo $user['user_name']; ?></a></p>
				<p class="time-people">
					<?php if(isset($user['freetime'])){
						foreach ($user['freetime'] as $value){
							echo $value['freetime_start'].' to '.$value['freetime_end'].'<br/>';
						}					
					}
					?>
				</p>
				<button id="<?php echo $user['user_id']; ?>" class="btn btn-primary hangout-people">Let's Hang Out</button>
			</div>
		<?php endforeach;?>
	</div>
	<div class="user-list clearfix">
		<p>Hang out with:</p>
	</div>
	<form method="post">
		<input type="hidden" name="users" value=""></input>
		<button type="submit" class="btn btn-warning float-right btn-next-people">Next   <span class="glyphicon glyphicon-circle-arrow-right"></span></button>
	</form>
</section>